FROM carlasim/carla:0.9.9.4
USER root
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    libpng16-16 \
    libjpeg8 \
    libtiff5 \
    && rm -rf /var/lib/apt/lists/*
RUN pip3 install numpy pygame
WORKDIR /home/carla
USER carla
ENTRYPOINT ["/bin/bash", "-c", \
  "SDL_VIDEODRIVER=x11 ./CarlaUE4.sh -opengl -quality-level=Low -nosound -carla-rpc-port=2000 -benchmark -fps=20"]
